# -*- mode: ruby -*-
# vi: set ft=ruby :

SERVER_MEMORY = "512"
VMNAME = "expressifvm"

PGPORT = "5432"
PGUSER = "postgres"
PGPASSWORD = "devved"
PGDATABASE = "testdb"
PGVERSION = "10"
NODE_VER = "10.x"
DB_DIR="/home/vagrant/comlog/migrations/"

$script = <<SCRIPT
echo I am provisioning...
date > /etc/vagrant_provisioned_at
ETH0IP=$(ifconfig -a eth0 | grep "inet addr:")
echo "Networking: [$ETH0IP]"
SCRIPT

Vagrant.configure("2") do |config|


	config.vm.provider "virtualbox" do |vb, orvb|
		orvb.vm.box = "bento/ubuntu-16.04"
		orvb.vm.synced_folder '../', '/home/vagrant/expressif', create:true, :mount_options => ['dmode=775', 'fmode=777']
		orvb.vm.network "private_network", ip: "192.168.86.8"
		vb.memory = SERVER_MEMORY
		vb.customize ["modifyvm", :id, "--memory", SERVER_MEMORY]
	end

	config.vm.provider "hyperv" do |hv, orhv|
		orhv.vm.box = "generic/ubuntu1604"
		orhv.vm.synced_folder "../", "/home/vagrant/expressif", create:true,
			type: "rsync", rsync__exclude: ".git/"
		orhv.vm.network "public_network"
		hv.memory = SERVER_MEMORY
		hv.maxmemory = SERVER_MEMORY
		hv.linked_clone = true
		hv.enable_virtualization_extensions = true
		hv.vmname = VMNAME
	end

	config.vm.define "expressifvm", primary:true do |comlog|
		comlog.vm.hostname = "expressifvm.test"
		comlog.vm.provision "shell", inline: $script
		comlog.vm.provision :shell do |s|
			s.path = "testbox.bootstrap.sh"
			s.env = {
				"PGPORT" => PGPORT,
				"PGUSER" => PGUSER,
				"PGPASSWORD" => PGPASSWORD,
				"PGDATABASE" => PGDATABASE,
				"PGVERSION" => PGVERSION,
				"NODE_VER" => NODE_VER
			}
		end
	end
end
